# Generated by Django 2.0.5 on 2018-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=6)),
                ('sampleRate', models.PositiveSmallIntegerField()),
                ('bitsPerSample', models.PositiveSmallIntegerField()),
                ('bitrateMode', models.CharField(max_length=3)),
                ('format1', models.CharField(max_length=10)),
                ('quality', models.PositiveSmallIntegerField()),
                ('channel', models.PositiveSmallIntegerField()),
                ('bitrate', models.PositiveSmallIntegerField()),
                ('server', models.URLField()),
                ('port', models.PositiveSmallIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('mountPoint', models.CharField(max_length=20)),
            ],
        ),
    ]
