# Generated by Django 2.0.5 on 2018-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20180821_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifi',
            name='SSID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
