# Generated by Django 2.0.5 on 2018-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='conf', max_length=10),
            preserve_default=False,
        ),
    ]
