# Generated by Django 2.0.5 on 2018-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkice', '0002_config_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='format1',
            new_name='format',
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
