# Generated by Django 2.0.5 on 2018-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkice', '0003_auto_20180825_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='channel_icecast',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mono'), (2, 'Stereo')], default=2),
        ),
        migrations.AlterField(
            model_name='config',
            name='channel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mono'), (2, 'Stereo')], default=2),
        ),
    ]
