# Generated by Django 2.0.5 on 2018-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkice', '0004_auto_20180825_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='bitrate',
            field=models.PositiveSmallIntegerField(choices=[(96, '96Kbps'), (128, '128Kbps'), (160, '160Kbps'), (192, '192Kbps'), (320, '96Kbps')], default=128, help_text='Tasa de bits por segundo de la codificación'),
        ),
        migrations.AlterField(
            model_name='config',
            name='bitrateMode',
            field=models.CharField(choices=[('cbr', 'cbr'), ('abr', 'abr'), ('vbr', 'vbr')], help_text='Modo de la tasa de bits de la codificación', max_length=3),
        ),
        migrations.AlterField(
            model_name='config',
            name='bitsPerSample',
            field=models.PositiveSmallIntegerField(choices=[(16, '16 (for mono feeds)'), (32, '32 (for stereo feeds)')], default=16, help_text='Bits por muestra'),
        ),
        migrations.AlterField(
            model_name='config',
            name='channel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mono'), (2, 'Stereo')], default=2, help_text='Mono o estéreo'),
        ),
        migrations.AlterField(
            model_name='config',
            name='channel_icecast',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mono'), (2, 'Stereo')], default=2, help_text='Número de canales de la salida, mono o estéreo'),
        ),
        migrations.AlterField(
            model_name='config',
            name='device',
            field=models.CharField(help_text='Dispositivo de grabación', max_length=6),
        ),
        migrations.AlterField(
            model_name='config',
            name='format',
            field=models.CharField(choices=[('vorbis', 'vorbis'), ('mp3', 'mp3'), ('mp2', 'mp2'), ('aac', 'aac'), ('aacp', 'aacp')], default='mp3', help_text='Formato del flujo enviado a Icecast', max_length=3),
        ),
        migrations.AlterField(
            model_name='config',
            name='mountPoint',
            field=models.CharField(help_text='Punto de montaje en servidor Icecast', max_length=20),
        ),
        migrations.AlterField(
            model_name='config',
            name='password',
            field=models.CharField(help_text='Clave para conectar al servidor Icecast', max_length=20),
        ),
        migrations.AlterField(
            model_name='config',
            name='port',
            field=models.PositiveSmallIntegerField(default=8000, help_text='Puerto del servidor Icecast'),
        ),
        migrations.AlterField(
            model_name='config',
            name='quality',
            field=models.DecimalField(choices=[(0.0, '0.0'), (0.1, '0.1'), (0.2, '0.2'), (0.3, '0.3'), (0.4, '0.4'), (0.5, '0.5'), (0.6, '0.6'), (0.7, '0.7'), (0.8, '0.8'), (0.9, '0.9'), (1.0, '1.0')], decimal_places=1, default=1.0, help_text='Calidad de la codificación, 1.0 máxima calidad', max_digits=2),
        ),
        migrations.AlterField(
            model_name='config',
            name='sampleRate',
            field=models.PositiveSmallIntegerField(choices=[(11025, '11025 Hz'), (22050, '22050 Hz'), (44100, '44100 Hz'), (48000, '48000 Hz')], default=44100, help_text='Frecuencia de muestreo de la grabación'),
        ),
        migrations.AlterField(
            model_name='config',
            name='server',
            field=models.URLField(help_text='URL del servidor Icecast'),
        ),
    ]
